% Dokumentklasse für FHNW Projektarbeiten
% Authoren: Mathias Graf, Jean-Paul John

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{profhnw}

\ProcessOptions\relax

\LoadClass[a4paper]{article}


\RequirePackage[margin=2.5cm]{geometry}
\RequirePackage[utf8]{inputenc}
\RequirePackage{graphicx}
\RequirePackage[backend=bibtex]{biblatex}
\RequirePackage{fancyhdr}
\RequirePackage{filecontents}
\RequirePackage[ngerman]{babel}
\RequirePackage[ngerman]{cleveref}
\RequirePackage{textcomp}
\RequirePackage{placeins}
\RequirePackage{capt-of}
\RequirePackage{longtable}
\RequirePackage{lscape}
\RequirePackage{pdfpages}


\pagestyle{fancy}

\endinput
